config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'
  get 'subscription/new'
  root 'blog_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'customers/new'
  get 'help'    =>  'blog_pages#help'
  get 'favorites'    =>  'blog_pages#favorites'
  get 'about'   =>  'blog_pages#about'
  get 'contact' =>  'blog_pages#contact'
  get 'signup'  =>  'customers#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post 'blog_pages/group_message', to: 'blog_pages#group_message'
  post 'blog_pages/privat_message', to: 'blog_pages#privat_message'
  post 'blog_pages/send_message', to: 'blog_pages#send_message', as: 'send_message'
  get 'results', to: 'results#index', as: 'results'
  get 'search', to: 'results#index', as: 'search'
  get 'roomlist' => 'rooms#roomlist'
  get 'personal' => 'rooms#personal'
  get 'single_show/:id', to: 'rooms#single_show', as: 'single_show'
  get 'payment_method' => 'rooms#payment_method'

  resources :customers do
    member do
      get :following, :followers
    end
  end
  resource :blacklist, only: %i[show destroy] do
    resources :items, only: %i[create destroy]
  end
  resources :reviews
  resources :posts
  resources :rooms
  resources :microposts
  resources :telechannels
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :incoming_mails, only: [:create]

end

app/controllers/blog_pages_controller.rb
class BlogPagesController < ApplicationController

  def home
    @carousel_rooms_first = Room.where(carousel: 'true').first
    @carousel_rooms_second = Room.where(carousel: 'true').second
    @carousel_rooms_last = Room.where(carousel: 'true').last
    @microposts = Micropost.all.limit(3)
    @telechannels = Telechannel.last(3)
    @pagy, @rooms = pagy(Room.where(hot: 'true'))
  end

  def help
  end

  def about
  end

  def contact
  end

  def favorites
  end

  def group_message
    chat_id = -634155082
    text = "Hi all!"
    HTTParty.post("https://api.telegram.org/bot#{TELEGRAM}/sendMessage",
      headers: {
        'Content-type' => 'application/json'
      },
      body: {
        chat_id: chat_id,
        text: text
      }.to_json
    )
    redirect_to root_path, notice: 'Сообщение отправлено!'
  end

  def privat_message
    chat_id = 1961648829
    text = "Hi Andrew!"
    HTTParty.post("https://api.telegram.org/bot#{TELEGRAM}/sendMessage",
      headers: {
        'Content-type' => 'application/json'
      },
      body: {
        chat_id: chat_id,
        text: text
      }.to_json
    )
    redirect_to root_path, notice: 'Сообщение отправлено!'
  end

  def send_message
    text = params[:content]
    TelegramMailer.send_group_message(text).deliver_now
    redirect_to root_path, notice: 'Сообщение отправлено!'
  end
end

app/helpers/blog_pages_helper.rb
module BlogPagesHelper
end

app/views/blog_pages/about.html.haml
- provide(:title, 'About')
%h2
 Без посредников! Из рук в Руки! Продавайте, покупайте, размещайте и находите каналы, боты или услуги!
 Договаривайтесь напрямую с помощью удобно встроеного сервиса сообщений!
 Оставляйте честные отзывы на нашем удобном сайте TelegaGid!

app/views/blog_pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact
%p
  Contact the Blog with Black List about the sample app at the
  %a{:href => "https://github.com/wishka/BlackListBlog"} contact page.

app/views/blog_pages/favorites.html.haml
%h1 Избранное

app/views/blog_pages/help.html.haml
- provide(:title, 'Help')
This is a
%a{:href => "https://github.com/wishka/BlackListBlog"} Help page
of Blog with Black List

app/views/blog_pages/home.html.haml
- provide(:title, 'Home')
.container.center
  %h4.ad-head.text-black.text-uppercase.mb-3
    %h2.head-title У нас вы можете найти, разместить, продать или купить канал, чат, бота или даже услугу
    #header-carousel.carousel.slide.carousel-fade{"data-bs-ride" => "carousel"}
      .carousel-inner
        .carousel-item.active
          - if @carousel_rooms_first.present?
            %img
              = image_pack_tag '1.jpeg', class:"carousel-img"
            .carousel-caption.d-flex.flex-column.align-items-center.justify-content-center
            .p-1{:style => "max-width: 400px;"}
              %h5.mb-md-4.animated.zoomIn.content-block
                = image_pack_tag '1.jpeg', class:"carousel-img-mini"
                %b= @carousel_rooms_first.name
                = image_pack_tag '1.jpeg', class:"carousel-img-mini"
                %em.truncate-carousel= @carousel_rooms_first.content
                .carousel-link= link_to @carousel_rooms_first.link, @carousel_rooms_first.link
          - else
            %img
              = image_pack_tag "carousel-1.jpg", class:"w-100"
              .carousel-caption.d-flex.flex-column.align-items-center.justify-content-center
              .p-1{:style => "max-width: 900px;"}
                %h3.display-4.text-white.mb-md-4.animated.zoomIn
                  = link_to 'Читать', '/rooms/1'
        .carousel-item
          - if @carousel_rooms_second.present?
            %img
              = image_pack_tag '2.jpeg', class:"carousel-img"
            .carousel-caption.d-flex.flex-column.align-items-center.justify-content-center
            .p-1{:style => "max-width: 400px;"}
              %h5.mb-md-4.animated.zoomIn.content-block
                = image_pack_tag '2.jpeg', class:"carousel-img-mini"
                %b= @carousel_rooms_second.name
                = image_pack_tag '2.jpeg', class:"carousel-img-mini"
                %em.truncate-carousel= @carousel_rooms_second.content
                .carousel-link= link_to @carousel_rooms_second.link, @carousel_rooms_second.link
          - else
            %img
              = image_pack_tag "carousel-1.jpg", class:"w-100"
              .carousel-caption.d-flex.flex-column.align-items-center.justify-content-center
              .p-1{:style => "max-width: 900px;"}
                %h3.display-4.text-white.mb-md-4.animated.zoomIn
                  = link_to 'Читать', '/rooms/1'
        .carousel-item
          - if @carousel_rooms_last.present?
            %img
              = image_pack_tag '3.jpeg', class:"carousel-img"
            .carousel-caption.d-flex.flex-column.align-items-center.justify-content-center
            .p-1{:style => "max-width: 400px;"}
              %h5.mb-md-4.animated.zoomIn.content-block
                = image_pack_tag '3.jpeg', class:"carousel-img-mini"
                %b= @carousel_rooms_last.name
                = image_pack_tag '3.jpeg', class:"carousel-img-mini"
                %em.truncate-carousel= @carousel_rooms_last.content
                .carousel-link= link_to @carousel_rooms_last.link, @carousel_rooms_last.link
          - else
            %img
              = image_pack_tag "carousel-1.jpg", class:"w-100"
              .carousel-caption.d-flex.flex-column.align-items-center.justify-content-center
              .p-1{:style => "max-width: 900px;"}
                %h3.display-4.text-white.mb-md-4.animated.zoomIn
                  = link_to 'Читать', '/rooms/1'

      %button.carousel-control-prev{"data-bs-slide" => "prev", "data-bs-target" => "#header-carousel", :type => "button"}
        %span.carousel-control-prev-icon{"aria-hidden" => "true"}
        %span.visually-hidden Предыдущее
      %button.carousel-control-next{"data-bs-slide" => "next", "data-bs-target" => "#header-carousel", :type => "button"}
        %span.carousel-control-next-icon{"aria-hidden" => "true"}
        %span.visually-hidden Следующее
        / Navbar & Carousel End


  %br
  .container-fluid
    = form_tag results_path, method: :get, role: 'search' do
      = text_field_tag :query, params[:query], placeholder: "Поиск по ключевому слову...", class: 'seacrhfrom'
      = submit_tag "Искать!", name: nil, class: 'searchbtn', style: 'font-size: 0.7rem'
      

  .container-fluid.bg-dark.text-light.mt-5.wow.fadeInUp{"data-wow-delay" => "0.1s"}
    .container
      .row
        .col-lg-12.col-md-12.footer-about
          .d-flex.flex-column.justify-content-center.text-center.h-100.bg-primary.p-4
            %a.navbar-brand{:href => root_path}
              %h1.text-white
                %i.fas.fa-user-tie.me-2
                Telegagid
            %p.mt-3.mb-4 Для размещения канала/бота/услуги в каруселе на главной странице сайта, просто напишите нашему менеджеру и получите полный рекламный прайс
            = form_tag send_message_path, method: :post do
              .input-group
                = text_field_tag :content, nil, required: true, class: "form-control", style: "border-white p-3"
                %button.btn.btn-dark= "Отправить"



  %h2.head-title Последние объявления
  %br
  .container-fluid
    = render 'rooms/room'
  %br

  %h2.head-title Полезная информация

  .container-fluid
    = render 'microposts/microposts'
  %br



    /= button_to "Send group message via controller", blog_pages_group_message_path
    /= button_to "Send private message via controller", blog_pages_privat_message_path

    /= form_tag send_message_path, method: :post do
    /  = text_field_tag :content, nil, required: true
    /  %hr
    /  = submit_tag "Say hello"

    /= params[:id]
    /= params[:first_name]
    /= params[:last_name]
    /= params[:customername]
    /= params[:auth_date]
    /= params[:hash]