config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'
  get 'subscription/new'
  root 'blog_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'customers/new'
  get 'help'    =>  'blog_pages#help'
  get 'favorites'    =>  'blog_pages#favorites'
  get 'about'   =>  'blog_pages#about'
  get 'contact' =>  'blog_pages#contact'
  get 'signup'  =>  'customers#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post 'blog_pages/group_message', to: 'blog_pages#group_message'
  post 'blog_pages/privat_message', to: 'blog_pages#privat_message'
  post 'blog_pages/send_message', to: 'blog_pages#send_message', as: 'send_message'
  get 'results', to: 'results#index', as: 'results'
  get 'search', to: 'results#index', as: 'search'
  get 'roomlist' => 'rooms#roomlist'
  get 'personal' => 'rooms#personal'
  get 'single_show/:id', to: 'rooms#single_show', as: 'single_show'
  get 'payment_method' => 'rooms#payment_method'

  resources :customers do
    member do
      get :following, :followers
    end
  end
  resource :blacklist, only: %i[show destroy] do
    resources :items, only: %i[create destroy]
  end
  resources :reviews
  resources :posts
  resources :rooms
  resources :microposts
  resources :telechannels
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :incoming_mails, only: [:create]

end

app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name,  presence: true, length: { maximum: 50 }
  validates :content,  presence: true
  has_many :posts, dependent: :delete_all
  has_many :customers, through: :posts
  has_many :cities
  belongs_to :customer
  before_save   :downcase_name
  include PgSearch
  pg_search_scope :search_everywhere, against: [:name, :content]

  filterrific(
    :default_filter_params => { },
    :available_filters => %w[
      sorted_by
      with_room_cat_route
      with_room_route
      with_room_city
      search_query
      with_room_category
      with_created_at_gte
    ])

  scope :sorted_by, ->(sort_option) {
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    rooms = Room.arel_table
    case sort_option.to_s
    when /^route/
      order("route #{ direction }")
    when /^created_at/
      order("created_at #{ direction }")
    when /^category/
      order("category #{ direction }")
    when /^cat_route/
      order("cat_route #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  scope :search_query, ->(query) {
    return nil  if query.blank?
    terms = query.downcase.split(/\s+/)
    terms = terms.map { |e|
      (e.tr("*", "%") + "%").gsub(/%+/, "%")
    }
    num_or_conds = 2
    where(
      terms.map { |_term|
        "(LOWER(rooms.name) LIKE ? OR LOWER(rooms.content) LIKE ?)"
      }.join(" AND "),
      *terms.map { |e| [e] * num_or_conds }.flatten,
    )
  }

  scope :with_room_cat_route, ->(room_cat_route) {
      where(
       'rooms.cat_route like :room_cat_route',
       room_cat_route: "%#{room_cat_route}%"
      )
    }

  scope :with_room_route, ->(room_route) {
      where(
       'rooms.route like :room_route',
       room_route: "%#{room_route}%"
      )
    }

   scope :with_room_city, ->(room_city) {
     where(
      'rooms.city like :room_city',
      room_city: "%#{room_city}%"
     )
   }

   scope :with_room_category, ->(room_category) {
     where(
      'rooms.category like :room_category',
      room_category: "%#{room_category}%"
     )
   }

   def self.options_for_sorted_by
    [
      ["Дата создания (сначала новые)", "created_at_desc"],
      ["Дата создания (сначала старые)", "created_at_asc"],
      ["Категория а-я", "category_asc"],
      ["Категория я-а", "category_desc"]
    ]
  end

  def self.cat_route_for_select
    rooms = Room.arel_table
    # order('LOWER(name)').map { |e| [e.name, e.id] }
    order(rooms[:cat_route].lower).pluck(:cat_route).uniq
  end

  def self.subdir_for_select
    rooms = Room.arel_table
    # order('LOWER(name)').map { |e| [e.name, e.id] }
    order(rooms[:subdir].lower).pluck(:subdir).uniq
  end

  def self.route_for_select
    rooms = Room.arel_table
    # order('LOWER(name)').map { |e| [e.name, e.id] }
    order(rooms[:route].lower).pluck(:route).uniq
  end

  def self.city_for_select
    rooms = Room.arel_table
    # order('LOWER(name)').map { |e| [e.name, e.id] }
    order(rooms[:city].lower).pluck(:city).uniq
  end

  def self.category_for_select
    rooms = Room.arel_table
    # order('LOWER(name)').map { |e| [e.name, e.id] }
    order(rooms[:category].lower).pluck(:category).uniq
  end

  private

  def self.sweep(time = 30.days)
    where("created_at < ?", time.ago.to_s(:db)).delete_all
    text = "Объявление: #{@room.name} будет удалено сегодня"
    TelegramMailer.send_group_message(text).deliver_now
  end

  def downcase_name
    self.name = name.downcase
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @pagy, @rooms = pagy(Room.all, items: 18)
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @rooms = Room.all
    render 'index'
    if @room = Room.find(params[:id])
    else
      render 'new'
    end
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)
    @room.customer_id = current_customer.id

    if @room.save
      redirect_to @room
        if @room.hot?
          flash[:notice] = "Успешно. Перейдите на страницу оплаты!"
        end

      SendMessageJob.perform_later(@room)

      text = "Новое объявление: #{@room.name}"
      TelegramMailer.send_group_message(text).deliver_now
    else
      render 'new'
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
        text = "Объявление изменено: #{@room.name}"
        TelegramMailer.send_group_message(text).deliver_now
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
      text = "Объявление удалено: #{@room.name}"
      TelegramMailer.send_group_message(text).deliver_now
    end
  end

  def roomlist
    @filterrific = initialize_filterrific(
       Room.all,
       params[:filterrific],
       select_options: {
        sorted_by: Room.options_for_sorted_by,
        with_room_cat_route: Room.cat_route_for_select,
        with_room_route: Room.route_for_select,
        with_room_city: Room.city_for_select,
        with_room_category: Room.category_for_select
       },
       persistence_id: "shared_key",
       default_filter_params: {
       },
       available_filters: [:sorted_by,
                           :search_query,
                           :with_room_cat_route,
                           :with_room_route,
                           :with_room_city,
                           :with_room_category],
       sanitize_params: true,
       ) || return

    @rooms = @filterrific.find

    @pagy, @rooms = pagy(@filterrific.find)

    respond_to do |format|
      format.html
    end

    rescue ActiveRecord::RecordNotFound => e
     # There is an issue with the persisted param_set. Reset it.
     puts "Had to reset filterrific params: #{e.message}"
     redirect_to(reset_filterrific_url(format: :html)) && return

  end

  def personal
    @pagy, @rooms = pagy(Room.joins(:customer).where(customer_id: current_customer.id))
    render 'personal'
  end

  def single_show
    @room = Room.find_by(id: params[:id])
  end

  def payment_method
    @pagy, @rooms = pagy(Room.where(hot: true))
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :content, :route,
                                   :cat_route, :subdir, :link, :category,
                                   :image, :followers, :image_cache, :remote_image_url,
                                   :city, :price, :hot, :big_size,
                                   :carousel, :free)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_list.html.haml
%h1 Список объявлений

.container-fluid
  .row
    .col-12
      %hr
        .row#filterrific_results
          - @rooms.each do |room|
            .col-md-4.room-view
              = image_tag room.image.url(:thumb), class: 'img-show' if room.image?
              %h4.text-primary
              - if room.hot == true
                = image_pack_tag 'flame.ico', class: 'img-litle'
                = link_to room.name, single_show_path(room)
              - elsif room.big_size == true
                = link_to room.name, single_show_path(room), class: 'big_size'
              - else
                = link_to room.name, single_show_path(room)
              - if room.city == "Не имеет значение"
                .d-none= room.city
              - else
                %p.m-0= room.city
              %p.truncate.m-0= room.content
              %p.m-0= room.price
              %p.m-0= room.created_at.to_date
              = link_to 'Посмотреть', single_show_path(room), class: 'btn btn-primary btn-block'
              = link_to 'Написать', room_path(room), class: 'btn btn-success btn-block'
        %br
= raw pagy_bootstrap_nav(@pagy).html_safe

app/views/rooms/_room.html.haml
.row
  - @rooms.each do |room|
    .col-md-4.room-view
      = image_tag room.image.url(:thumb), class: 'img-show' if room.image?
      %h4.text-primary
      - if room.hot == true
        = image_pack_tag 'flame.ico', class: 'img-litle'
        = link_to room.name, single_show_path(room)
      - elsif room.big_size == true
        = link_to room.name, single_show_path(room), class: 'big_size'
      - else
        = link_to room.name, single_show_path(room)
      - if room.city == "Не имеет значение"
        .d-none= room.city
      - else
        %p.m-0= room.city
      %p.truncate.m-0= room.content
      %p.m-0= room.price
      %p.m-0= room.created_at.to_date
      = link_to 'Посмотреть', single_show_path(room), class: 'btn btn-primary btn-block'
      = link_to 'Написать', room_path(room), class: 'btn btn-success btn-block'
%br
= raw pagy_bootstrap_nav(@pagy).html_safe

app/views/rooms/_roomlist.html.haml
%h2.head-title Поиск по объявлениям
%br
%p= link_to "Разместить", new_room_path, class: "btn btn-lg btn-outline-dark", style: 'width: 100%; border: none'
- puts @filterrific.inspect
= form_for_filterrific @filterrific do |f|
  .row
    .col-md-3
      .form-group
        = f.text_field(:search_query,
          class: 'filterrific-periodically-observed form-control')
    .col-md-3
      .form-group
        = f.select :with_room_cat_route,
                    @filterrific.select_options[:with_room_cat_route],
                    { :include_blank => "Что ищем?" },
                    { :class => 'form-control' }
    .col-md-3
      .form-group
        = f.select :with_room_route,
                    @filterrific.select_options[:with_room_route],
                    { :include_blank => 'Тип объявления' },
                    { :class => 'form-control' }
    .col-md-3
      .form-group
        = f.select :with_room_city,
                    @filterrific.select_options[:with_room_city],
                    { :include_blank => 'Город' },
                    { :class => 'form-control' }
    .col-md-3
      .form-group
        = f.select :with_room_category,
                    @filterrific.select_options[:with_room_category],
                    { :include_blank => 'Категория' },
                    { :class => 'form-control' }


    %p= f.submit "Показать", class: "btn btn-lg btn-outline-dark", style: 'width: 100%; border: none'

    %p= link_to('Сбросить фильтры',reset_filterrific_url, class: "btn btn-lg btn-outline-danger", style: 'width: 100%; border: none')
    = render_filterrific_spinner

#results= render :partial => 'rooms/list', :locals => { :rooms => @rooms }

app/views/rooms/edit.html.haml
- provide(:title, 'Редактирование объявления')
%h1 Редактирования объявления

= render 'form'

= link_to 'Показать', @room
\|
= link_to 'Назад', rooms_path

app/views/rooms/index.html.haml
- provide(:title, 'Объявления')
%h1 Список объявлений
#room-id{"data-room-id" => @room.try(:id)}
#customer-id{"data-customer-id" => current_customer.id}
.container-fluid
  .row
    .col-3.rooms-sidebar
      /%b Создать новое объявление
      /= render 'form', room: Room.new
      %hr
      - @rooms.each do |room|
        .room-link
          = link_to room do
            .card.mb-2.room-card
              .card-body
                %span.name
                  = room.name
                  - if room.customer_id == current_customer.id || current_customer.admin?
                    = link_to 'Удалить', room, method: :delete, data: { confirm: 'Are you sure?' }
                    = link_to 'Редактировать', edit_room_path(room)
    .col-9
      - if @room.present?
        .chat-room
          = @room.name
          = image_tag @room.image.url(:thumb), class: 'img-show' if @room.image?
          #messages
            - @room.posts.each do |post|
              = render 'posts/post', post: post
          .chat-box
            = render 'posts/form', post: Post.new, room: @room

app/views/rooms/index.js.erb
<% js = escape_javascript(
  render(partial: 'rooms/list', locals: { rooms: @rooms })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/rooms/new.html.haml
- provide(:title, 'New room')
%h1 Новое объявление

= render 'form'

= link_to 'Назад', rooms_path

app/views/rooms/payment_method.html.haml
- provide(:title, 'Страница оплаты')
%h2 Ожидают оплаты:
= raw pagy_bootstrap_nav(@pagy).html_safe
- @rooms.each do |room|
  = link_to room.name
  = link_to 'Оплатить', payments_new_path, class: 'btn btn-sm btn-outline-primary'
  %br
%br
= raw pagy_bootstrap_nav(@pagy).html_safe

app/views/rooms/personal.html.haml
- provide(:title, 'Personal messages')

%h1 Мои объявления
= raw pagy_bootstrap_nav(@pagy).html_safe
#room-id{"data-room-id" => @room.try(:id)}
#customer-id{"data-customer-id" => current_customer.id}
.container-fluid
  .row
    .col-9
      %hr
      #filterrific_results
        %table.filter
          %tr
            %th
            %th Название
            %th Категория
            %th Дата создания
            %hr
          - @rooms.each do |room|
            %tr
              %td= image_tag room.image.url(:thumb), class: 'img-show' if room.image?
              %td= link_to room.name, room
              %td= room.category
              %td= room.created_at.to_date
%hr
= raw pagy_bootstrap_nav(@pagy).html_safe

app/views/rooms/roomlist.html.haml
%h2.head-title Поиск по объявлениям
%br
%p= link_to "Разместить", new_room_path, class: "btn btn-lg btn-outline-dark", style: 'width: 100%; border: none'
- puts @filterrific.inspect
= form_for_filterrific @filterrific do |f|
  .row
    .col-md-3
      .form-group
        = f.text_field(:search_query,
          class: 'filterrific-periodically-observed form-control')
    .col-md-3
      .form-group
        = f.select :with_room_cat_route,
                    @filterrific.select_options[:with_room_cat_route],
                    { :include_blank => "Что ищем?" },
                    { :class => 'form-control' }
    .col-md-3
      .form-group
        = f.select :with_room_route,
                    @filterrific.select_options[:with_room_route],
                    { :include_blank => 'Тип объявления' },
                    { :class => 'form-control' }
    .col-md-3
      .form-group
        = f.select :with_room_city,
                    @filterrific.select_options[:with_room_city],
                    { :include_blank => 'Город' },
                    { :class => 'form-control' }
    .col-md-3
      .form-group
        = f.select :with_room_category,
                    @filterrific.select_options[:with_room_category],
                    { :include_blank => 'Категория' },
                    { :class => 'form-control' }


    %p= f.submit "Показать", class: "btn btn-lg btn-outline-dark", style: 'width: 100%; border: none'

    %p= link_to('Сбросить фильтры',reset_filterrific_url, class: "btn btn-lg btn-outline-danger", style: 'width: 100%; border: none')
    = render_filterrific_spinner

#results= render :partial => 'rooms/list', :locals => { :rooms => @rooms }

app/views/rooms/show.html.haml
- provide(:title, 'Room show')
%p#notice= notice

%p
  %b Name:
  = image_tag @room.image.url(:large), class: 'img-show' if @room.image?
  = @room.name
  = @room.content


  = link_to 'Редактировать', edit_room_path(@room)
\|
= link_to 'Назад', rooms_path

app/views/rooms/single_show.html.haml
- provide(:title, "Объявление № #{@room_id}")
%p#notice= notice

%p= image_tag @room.image.url(:large), class: 'img-s-show' if @room.image?
%p
  %h2= @room.name
%p
  .small Ссылка:
  %b= link_to @room.link, @room.link if @room.link?
%p
  .small Город:
  %b= @room.city
%p
  .small Категория:
  %b= @room.category
%p
  .small Цена:
  %b= @room.price if @room.price?
%p
  .small Описание:
  %b= @room.content

= link_to 'Назад', root_path, class: 'btn btn-primary btn-block'
= link_to 'Написать', room_path(@room), class: 'btn btn-success btn-block'
%br
%br