config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'
  get 'subscription/new'
  root 'blog_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'customers/new'
  get 'help'    =>  'blog_pages#help'
  get 'favorites'    =>  'blog_pages#favorites'
  get 'about'   =>  'blog_pages#about'
  get 'contact' =>  'blog_pages#contact'
  get 'signup'  =>  'customers#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post 'blog_pages/group_message', to: 'blog_pages#group_message'
  post 'blog_pages/privat_message', to: 'blog_pages#privat_message'
  post 'blog_pages/send_message', to: 'blog_pages#send_message', as: 'send_message'
  get 'results', to: 'results#index', as: 'results'
  get 'search', to: 'results#index', as: 'search'
  get 'roomlist' => 'rooms#roomlist'
  get 'personal' => 'rooms#personal'
  get 'single_show/:id', to: 'rooms#single_show', as: 'single_show'
  get 'payment_method' => 'rooms#payment_method'

  resources :customers do
    member do
      get :following, :followers
    end
  end
  resource :blacklist, only: %i[show destroy] do
    resources :items, only: %i[create destroy]
  end
  resources :reviews
  resources :posts
  resources :rooms
  resources :microposts
  resources :telechannels
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :incoming_mails, only: [:create]

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  belongs_to :room, dependent: :destroy
  #default_scope -> { order(created_at: :desc) }
  validates :customer_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.customer = current_customer
    @post.save
    redirect_to request.referrer

    SendMessageJob.perform_later(@post)
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :room_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_with(model: post, local: true) do |f|
  - if @post && @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.hidden_field :room_id, value: room.id

  .input-group
    = f.text_area :content, placeholder: 'Ваше сообщение...', class: 'form-control', style: 'width: 100%'

  .actions
    = f.submit 'Отправить', class: 'btn btn-primary', style: 'width: 100%'

app/views/posts/_post.html.haml
- provide(:title, 'Message')
.message.mb-2
  .content-container
    .author
      - if post.customer == current_customer
        = 'вы'
      - else
        | #{link_to post.customer.name, customer_path}
      .content
        = post.content
        - if post.customer_id == current_customer.id || current_customer.admin?
          = link_to 'Удалить', post, method: :delete

app/views/posts/edit.html.haml
- provide(:title, 'Edit message')
%h1 Редактирование сообщения

= render 'form'

= link_to 'Показать', @post
\|
= link_to 'Назад', posts_path

app/views/posts/index.html.haml
- provide(:title, 'Messages')
%h1 Сообщения
- if logged_in?
  - if current_customer.admin? && !current_customer?(@customer)
    %table
      %thead
        %tr
          %th Содержание
          %th Автор
          %th Название
          %th
          %th

      %tbody
        - @posts.each do |post|
          %tr
            %td= post.content
            %td= post.customer.name
            %td= link_to post.room.name, post.room
            %td= link_to 'Редактировать', edit_post_path(post)
            %td= link_to 'Удалить', post, method: :delete, data: { confirm: 'Are you sure?' }

    %br
  - else
    %table
      %thead
        %tr
          %th Содержание
          %th Название
          %th
          %th
          %th

      %tbody
        - @posts.each do |post|
          %tr
            %td= post.content
            %td= link_to post.room.name, post.room
            - if post.customer_id == current_customer.id || current_customer.admin?
              %td= link_to 'Редактировать', edit_post_path(post)
              %td= link_to 'Удалить', post, method: :delete, data: { confirm: 'Are you sure?' }

    %br
- else
  %li= link_to "Войти", login_path
  = link_to 'New Post', new_post_path

app/views/posts/mine.html.haml
.message.mb-2
  .content-container
    .author.me
        | #{post.customer.name}
      .content
        = post.content
        = link_to 'Удалить', post, method: :delete

app/views/posts/new.html.haml
- provide(:title, 'New message')
%h1 Новое сообщение

= render 'form'

= link_to 'Назад', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Содержание:
  = @post.content
%p
  %b Гость:
  = @post.customer.name
%p
  %b Объявление:
  = @post.room.name

= link_to 'Редактировать', edit_post_path(@post)
\|
= link_to 'Назад', posts_path

app/views/posts/theirs.html.haml
.message.mb-2
  .content-container
    .author
        | #{post.customer.name}
      .content
        = post.content
        = link_to 'Удалить', post, method: :delete