config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'
  get 'subscription/new'
  root 'blog_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'customers/new'
  get 'help'    =>  'blog_pages#help'
  get 'favorites'    =>  'blog_pages#favorites'
  get 'about'   =>  'blog_pages#about'
  get 'contact' =>  'blog_pages#contact'
  get 'signup'  =>  'customers#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post 'blog_pages/group_message', to: 'blog_pages#group_message'
  post 'blog_pages/privat_message', to: 'blog_pages#privat_message'
  post 'blog_pages/send_message', to: 'blog_pages#send_message', as: 'send_message'
  get 'results', to: 'results#index', as: 'results'
  get 'search', to: 'results#index', as: 'search'
  get 'roomlist' => 'rooms#roomlist'
  get 'personal' => 'rooms#personal'
  get 'single_show/:id', to: 'rooms#single_show', as: 'single_show'
  get 'payment_method' => 'rooms#payment_method'

  resources :customers do
    member do
      get :following, :followers
    end
  end
  resource :blacklist, only: %i[show destroy] do
    resources :items, only: %i[create destroy]
  end
  resources :reviews
  resources :posts
  resources :rooms
  resources :microposts
  resources :telechannels
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :incoming_mails, only: [:create]

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  mount_uploader :image, ImageUploader
  include PgSearch
  validates :title, :content, :image, presence: true
  pg_search_scope :search_everywhere, against: [:title]
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[ show edit update destroy ]

  # GET /microposts or /microposts.json
  def index
    @pagy, @microposts = pagy(Micropost.all, items: 10)
  end

  # GET /microposts/1 or /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to micropost_url(@micropost), notice: "Micropost was successfully created." }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to micropost_url(@micropost), notice: "Micropost was successfully updated." }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url, notice: "Micropost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:title, :content, :body, :image)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.haml
= form_for @micropost, html: {multipart: true} do |f|
  - if @micropost.errors.any?
    #error_explanation
      %h2= "#{pluralize(@micropost.errors.count, "error")} prohibited this micropost from being saved:"
      %ul
        - @micropost.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.text_field :title, placeholder: 'Название', class: "form-control"
  %br
  .form-group
    = f.text_field :content, placeholder: 'Краткое содержание', class: "form-control"
  %br
  .form-group
    = f.text_field :body, placeholder: 'Полное содержание', class: "form-control"
  %br
  .form-group
    = f.file_field :image, class: "form-control"
  .actions
    = f.submit 'Сохранить', class: "form-control"

app/views/microposts/_microposts.html.haml
%table
  %thead
    %tr
      %th
      %th Название
      %th Краткое содержание

  %tbody.clearfix
    - @microposts.each do |micropost|
      %tr
        %td= image_tag micropost.image.url(:mid), class: 'img-thumnail thumb' if micropost.image?
        %td= micropost.title
        %td= link_to micropost.content, micropost

= link_to 'Читать все', microposts_path, class: 'btn btn-lg btn-outline-primary', style: 'width: 100%; border: none'

app/views/microposts/edit.html.haml
- provide(:title, 'Post edit')
%h1 Редактирование поста

= render 'form'

= link_to 'Показать', @micropost
\|
= link_to 'Назад', microposts_path

app/views/microposts/index.html.haml
- provide(:title, 'Post list')
%h1 Список постов
= raw pagy_bootstrap_nav(@pagy).html_safe
%table
  %thead
    %tr
      %th
      %th Название
      %th Краткое содержание
      %th
      %th
      %th

  %tbody.clearfix
    - @microposts.each do |micropost|
      %tr
        %td= image_tag micropost.image.url(:thumb), class: 'img-thumnail thumb' if micropost.image?
        %td= micropost.title
        %td= link_to micropost.content, micropost
        - if current_customer.admin? && !current_customer?(@customer)
          %td= link_to 'Редактировать', edit_micropost_path(micropost)
          %td= link_to 'Удалить', micropost, method: :delete, data: { confirm: 'Уверены?' }

%br
= raw pagy_bootstrap_nav(@pagy).html_safe
= link_to 'Новый пост', new_micropost_path, class: 'btn btn-lg btn-outline-primary', style: 'width: 100%; border: none'

app/views/microposts/new.html.haml
- provide(:title, 'Post new')
%h1 Новый пост

= render 'form'

= link_to 'Назад', microposts_path

app/views/microposts/show.html.haml
- provide(:title, 'Post show')
%p#notice= notice

%p
  %b Название:
  = @micropost.title
%p
  %b Изображение:
  = image_tag @micropost.image.url(:large), class: 'img-show' if @micropost.image?
%p
  %b Краткое содержание:
  = @micropost.content
%p
  %b Полное содержание:
  = @micropost.body


= link_to 'Редактировать', edit_micropost_path(@micropost)
\|
= link_to 'Назад', microposts_path